select json_build_object(
 'geometry_proposals',(select count(*) from ingest.zoning_geometry_correction),
 'geometry_events',(select count(*) from ingest.zoning_geometry_event),
 'accepted_geometry',(select count(*) from ingest.corrected_zoning_feature where correction_status='accepted'),
 'original_zoning_features',(select count(*) from ingest.zoning_feature),
 'original_invalid_zoning',(select count(*) from ingest.zoning_feature where geometry_state='invalid'),
 'effective_invalid_zoning',(select count(*) from ingest.corrected_zoning_feature where effective_geometry_state='invalid'),
 'historical_screenings',(select count(*) from ingest.zoning_screening),
 'revised_screenings',(select count(*) from ingest.zoning_screening_revision),
 'historical_needs_revisit',(select count(*) from ingest.zoning_screening_current where needs_revisit),
 'revision_needs_revisit',(select count(*) from ingest.zoning_screening_revision_current where needs_revisit),
 'default_screenings',(select count(*) from ingest.zoning_screening_latest),
 'default_needs_revisit',(select count(*) from ingest.zoning_screening_latest where needs_revisit),
 'default_intersections',(select sum(jsonb_array_length(result->'intersections')) from ingest.zoning_screening_latest),
 'default_holds',(select count(*) from ingest.zoning_screening_latest where input->'holds'<>'[]'::jsonb),
 'legal_unknown',(select count(*) from ingest.zoning_screening_latest where result->>'legal_zoning_state'='UNKNOWN'),
 'source_records',(select count(*) from ingest.source_record),
 'assessment_candidates',(select count(*) from ingest.assessment_candidate),
 'findings',(select count(*) from ingest.finding),
 'finding_events',(select count(*) from ingest.finding_event),
 'finding',(select json_build_object('status',status,'occurrences',occurrence_count,'needs_revisit',needs_revisit) from ingest.finding_current where finding_id='TL-F-0025'),
 'rls_enabled',(select bool_and(relrowsecurity) from pg_class where oid in ('ingest.zoning_geometry_correction'::regclass,'ingest.zoning_geometry_event'::regclass,'ingest.zoning_screening_revision'::regclass)),
 'client_access_denied',not has_table_privilege('anon','ingest.zoning_screening_latest','SELECT') and not has_table_privilege('authenticated','ingest.corrected_zoning_feature','SELECT') and not has_function_privilege('service_role','ingest.record_zoning_geometry_event(jsonb,text)','EXECUTE'),
 'bucket_private',(select not public from storage.buckets where id='terralucid-source-snapshots')
) as verification;
